apiVersion: v2
name: mercure
description: A Helm chart to install a Mercure Hub in a Kubernetes cluster. Mercure is a protocol to push data updates to web browsers and other HTTP clients in a convenient, fast, reliable and battery-efficient way.
home: https://mercure.rocks
icon: https://mercure.rocks/static/logo.svg
sources:
- https://github.com/culy247/mercure
keywords:
- mercure
- hub
- push
- streaming-api
- async-api
type: application
version: 0.13.0
appVersion: "v0.13.0"
maintainers:
  - name: culy247
    email: kevin@culy247.fr
    url: https://culy247.fr
